### ISSUE TITLE
Model parallel training,multi gpus for one sample training

### ISSUE THREAD

**Issue by Machine-NO-Learning** [open-mmlab/OpenPCDet#1523]
I find even I use only batchsize=1  it is still out of memory, if not to change model,  how to use multi gpus for one sample training?

thanx

**Comment by 751K** [comment]
it‘s easy to use multi gpus for mmlab projects. You can consult the documentation of their other projects to find the right way, which is universal.

**Comment by 2021zyz** [comment]
I had the same problem and the solution was to enable fp16, as indicated in readme.md
