### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by hughlee815** [open-mmlab/OpenPCDet#273]
hi,
when i run test.py, it throws such an error:
Error!
Traceback (most recent call last):
  File "test.py", line 200, in <module>
    main()
  File "test.py", line 196, in main
    eval_single_ckpt(model, test_loader, args, eval_output_dir, logger, epoch_id, dist_test=dist_test)
  File "test.py", line 62, in eval_single_ckpt
    eval_utils.eval_one_epoch(
  File "/home/nio/Desktop/pointpillar/tools/eval_utils/eval_utils.py", line 57, in eval_one_epoch
    pred_dicts, ret_dict = model(batch_dict)
  File "/home/nio/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nio/Desktop/pointpillar/pcdet/models/detectors/pointpillar.py", line 21, in forward
    pred_dicts, recall_dicts = self.post_processing(batch_dict)
  File "/home/nio/Desktop/pointpillar/pcdet/models/detectors/detector3d_template.py", line 261, in post_processing
    recall_dict = self.generate_recall_record(
  File "/home/nio/Desktop/pointpillar/pcdet/models/detectors/detector3d_template.py", line 298, in generate_recall_record
    iou3d_rcnn = iou3d_nms_utils.boxes_iou3d_gpu(box_preds[:, 0:7], cur_gt[:, 0:7])
  File "/home/nio/Desktop/pointpillar/pcdet/ops/iou3d_nms/iou3d_nms_utils.py", line 71, in boxes_iou3d_gpu
    overlaps_h = torch.clamp(min_of_max - max_of_min, min=0)
RuntimeError: CUDA error: invalid device function

looking forward to your reply...

**Comment by deanzhanggit** [comment]
same problem

**Comment by MartinHahner88** [comment]
on which GPU are you trying to run `test.py`? Is the GPU based on the _Maxwell_ or on a newer architecture?

**Comment by deanzhanggit** [comment]
I use Tesla V100 and CUDA10.1

**Comment by MartinHahner88** [comment]
Are you able to try CUDA 9.2?

**Comment by deanzhanggit** [comment]
Thank you for your reply, I'll try it later.

**Comment by deanzhanggit** [comment]
I tried CUDA 9.2, problem solved！

**Comment by QAQAQAQAQAQ** [comment]
Hi,

When I run demo.py I got a similar cuda error:

`[Exception|implicit_gemm_pair]indices=torch.Size([11829, 4]),bs=1,ss=[  41 1600 1408],algo=ConvAlgo.MaskImplicitGemm,ksize=[3, 3, 3],stride=[1, 1, 1],padding=[1, 1, 1],dilation=[1, 1, 1],subm=True,transpose=False
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
  File "demo.py", line 118, in <module>
    main()
  File "demo.py", line 106, in main
    pred_dicts, _ = model.forward(data_dict)
  File "/home/wen/Documents/PointCloudDet/OpenPCDet/pcdet/models/detectors/voxel_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wen/Documents/PointCloudDet/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone.py", line 148, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/modules.py", line 137, in forward
    input = module(input)
  File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/conv.py", line 410, in forward
    raise e 
  File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/conv.py", line 401, in forward
    timer=input._timer)
  File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/ops.py", line 376, in get_indice_pairs_implicit_gemm
    mask_argsort_tv[j], stream)
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDeviceFunction: invalid device function
`


I tried cuda 9.2, 10.2, and 11.5 all getting the same error.
I am using a GM107GL [Quadro K620] GPU. I have read elsewhere that this error may be solved with a more powerful GPU, is it the case here?

Looking forward to your reply

**Comment by MartinHahner** [comment]
@FindDefinition: What is the status on Maxwell GPU support?

**Comment by FindDefinition** [comment]
@MartinHahner sm_50 now available in spconv-cu102>=2.1.16.

**Comment by twn29004** [comment]
> Hi,
> 
> When I run demo.py I got a similar cuda error:
> 
> `[Exception|implicit_gemm_pair]indices=torch.Size([11829, 4]),bs=1,ss=[ 41 1600 1408],algo=ConvAlgo.MaskImplicitGemm,ksize=[3, 3, 3],stride=[1, 1, 1],padding=[1, 1, 1],dilation=[1, 1, 1],subm=True,transpose=False SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue. Traceback (most recent call last): File "demo.py", line 118, in <module> main() File "demo.py", line 106, in main pred_dicts, _ = model.forward(data_dict) File "/home/wen/Documents/PointCloudDet/OpenPCDet/pcdet/models/detectors/voxel_rcnn.py", line 11, in forward batch_dict = cur_module(batch_dict) File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/wen/Documents/PointCloudDet/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone.py", line 148, in forward x = self.conv_input(input_sp_tensor) File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/modules.py", line 137, in forward input = module(input) File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/conv.py", line 410, in forward raise e File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/conv.py", line 401, in forward timer=input._timer) File "/home/wen/Documents/Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/ops.py", line 376, in get_indice_pairs_implicit_gemm mask_argsort_tv[j], stream) RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDeviceFunction: invalid device function `
> 
> I tried cuda 9.2, 10.2, and 11.5 all getting the same error. I am using a GM107GL [Quadro K620] GPU. I have read elsewhere that this error may be solved with a more powerful GPU, is it the case here?
> 
> Looking forward to your reply

Hi, have you solved the problem?

**Comment by QAQAQAQAQAQ** [comment]
Sort of. Yes. 
The error message changed to:
`[Exception|implicit_gemm]feat=torch.Size([11829, 4]),w=torch.Size([16, 3, 3, 3, 4]),pair=torch.Size([27, 11829]),act=11829,issubm=True,istrain=False
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
  File "demo.py", line 119, in <module>
    main()
  File "demo.py", line 107, in main
    pred_dicts, _ = model.forward(data_dict)
  File "/home/wen/Documents/PointCloudDet/OpenPCDet/pcdet/models/detectors/voxel_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wen/Documents/PointCloudDet/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone.py", line 148, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/modules.py", line 137, in forward
    input = module(input)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/conv.py", line 448, in forward
    input._timer)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/cuda/amp/autocast_mode.py", line 94, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/functional.py", line 197, in forward
    raise e 
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/functional.py", line 188, in forward
    is_train, is_subm, timer)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/ops.py", line 1116, in implicit_gemm
    stream=stream)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/algo.py", line 645, in tune_and_cache
    raise ValueError("can't find suitable algorithm for", op_type)
ValueError: ("can't find suitable algorithm for", <ConvOpType.kForward: 0>)

`

I used spconv-cu102==2.1.18
cuda==10.2
torch==1.10.0

I assumed I was using a different combination of packages so I also tried torch==1.4.0 & 1.6.0 (I did run setup.py again after that) but there seems to be a lot of dependency issues.

I see the [INSTALL.md](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/INSTALL.md) was updated.
> You could also install latest spconv v2.x with pip, see the official documents of spconv.
Is there a prerequisite for PyTorch version or can I just use anything?

**Comment by FindDefinition** [comment]
@QAQAQAQAQAQ fixed in cumm >= 0.2.6, you need to upgrade cumm by ```pip install -U cumm-cu102 -i https://pypi.python.org/simple``` after [build](https://github.com/FindDefinition/cumm/actions/runs/1533388129) finished.

**Comment by QAQAQAQAQAQ** [comment]
Thank you for your fast feedback.
I updated cumm but now I am getting cuda error 710 now

`
this arch isn't supported!
/io/build/temp.linux-x86_64-3.6/spconv/build/src/cumm/conv/main/Simt_f32f32f32f32f32tnt_m32n128k16m32n32k8_200_C301LLLA1_SK/ConvKernel/ConvKernel_conv_kernel.cu:104: void cumm::conv::main::Simt_f32f32f32f32f32tnt_m32n128k16m32n32k8_200_C301LLLA1_SK::conv_kernel(cumm::conv::main::cpSimt_f32f32f32f32f32tnt_m32n128k16m32n32k8_200_C301LLLA1_SK::ConvParams): block: [6,0,0], thread: [0,0,0] Assertion `0` failed.

......
/io/build/temp.linux-x86_64-3.6/spconv/build/src/cumm/conv/main/Simt_f32f32f32f32f32tnt_m32n128k16m32n32k8_200_C301LLLA1_SK/ConvKernel/ConvKernel_conv_kernel.cu:104: void cumm::conv::main::Simt_f32f32f32f32f32tnt_m32n128k16m32n32k8_200_C301LLLA1_SK::conv_kernel(cumm::conv::main::cpSimt_f32f32f32f32f32tnt_m32n128k16m32n32k8_200_C301LLLA1_SK::ConvParams): block: [6,0,0], thread: [158,0,0] Assertion `0` failed.
/io/build/temp.linux-x86_64-3.6/spconv/build/src/cumm/conv/main/Simt_f32f32f32f32f32tnt_m32n128k16m32n32k8_200_C301LLLA1_SK/ConvKernel/ConvKernel_conv_kernel.cu:104: void cumm::conv::main::Simt_f32f32f32f32f32tnt_m32n128k16m32n32k8_200_C301LLLA1_SK::conv_kernel(cumm::conv::main::cpSimt_f32f32f32f32f32tnt_m32n128k16m32n32k8_200_C301LLLA1_SK::ConvParams): block: [6,0,0], thread: [159,0,0] Assertion `0` failed.
[Exception|implicit_gemm]feat=torch.Size([40000, 4]),w=torch.Size([16, 3, 3, 3, 4]),pair=torch.Size([27, 40000]),act=40000,issubm=True,istrain=False
SPCONV_DEBUG_SAVE_PATH not found, you can specify SPCONV_DEBUG_SAVE_PATH as debug data save path to save debug data which can be attached in a issue.
Traceback (most recent call last):
  File "demo.py", line 114, in <module>
    main()
  File "demo.py", line 102, in main
    pred_dicts, _ = model.forward(data_dict)
  File "/home/wen/Documents/PointCloudDet/OpenPCDet/pcdet/models/detectors/voxel_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wen/Documents/PointCloudDet/OpenPCDet/pcdet/models/backbones_3d/spconv_backbone.py", line 148, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/modules.py", line 137, in forward
    input = module(input)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/conv.py", line 448, in forward
    input._timer)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/torch/cuda/amp/autocast_mode.py", line 94, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/functional.py", line 197, in forward
    raise e 
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/functional.py", line 188, in forward
    is_train, is_subm, timer)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/pytorch/ops.py", line 1116, in implicit_gemm
    stream=stream)
  File "/home/wen/Documents/EECS 498 Introduction to Algorithmic Robotics/HW3files/OpenPCDet/lib/python3.6/site-packages/spconv/algo.py", line 638, in tune_and_cache
    GemmMainUnitTest.stream_synchronize(stream)
RuntimeError: /io/build/temp.linux-x86_64-3.6/spconv/build/src/cumm/gemm/main/GemmMainUnitTest/GemmMainUnitTest_stream_synchronize.cc(11)
CUDA error 710
`
Thank you for your patience.

**Comment by FindDefinition** [comment]
@QAQAQAQAQAQ this problem should be fixed in spconv 2.1.19. upgrade and try again.

**Comment by QAQAQAQAQAQ** [comment]
Thank you so much!!! demo.py is working correctly right now.

**Comment by Yaccoub** [comment]
I am facing the same error while using it on google colab 
![image](https://user-images.githubusercontent.com/50803834/145142232-4411bab3-7e1b-4e15-9343-1a374a083850.png)

with the following configuration: 
CUDA = V10.2.89
torch = 1.10.0+cu102
spconv = 2.1.20 
Thank you for your help !

**Comment by FindDefinition** [comment]
@Yaccoub you are using K80 (sm_37) in colab which isn't supported by spconv prebuilts yet, will be added in spconv-cu102 2.1.21.

**Comment by YomnaGamal** [comment]
> @Yaccoub you are using K80 (sm_37) in colab which isn't supported by spconv prebuilts yet, will be added in spconv-cu102 2.1.21.

I'm using spconv-cu111  2.1.21 with K80, torch 1.10.0+cu111, torchvision 0.11.1+cu111 and the same error appears to me too.  
![image](https://user-images.githubusercontent.com/49347572/147373177-2d0341c7-6ede-4e7a-bdf1-8ecf5869a8b4.png)
any solution? 
Thanks.
