### ISSUE TITLE
PartA2 KITTI training error: cuda execution failed with error 700 an illegal memory access was encountered

### ISSUE THREAD

**Issue by sharma-n** [open-mmlab/OpenPCDet#338]
Hi,
First of all, thanks for sharing this work the modularization of the code is extremely helpful. I have been trying to train the PartA2 model but it leads to the following error being thrown within the first 50 batches (not always the same iteration):

```shell
Traceback (most recent call last):
  File "OpenPCDet/pcdet/models/roi_heads/partA2_head.py", line 200, in forward
    x_part = self.conv_part(part_features)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/spconv/conv.py", line 181, in forward
    use_hash=self.use_hash)
  File "/opt/conda/lib/python3.6/site-packages/spconv/ops.py", line 95, in get_indice_pairs
    int(use_hash))
RuntimeError: /OpenPCDet/spconv/src/spconv/indice.cu 274
cuda execution failed with error 700 an illegal memory access was encountered
prepareSubMGridKernel failed
```

I got this error by running the following command:
`CUDA_LAUNCH_BLOCKING=1 python train.py --cfg_file cfgs/kitti_models/PartA2.yaml`

The `CUDA_LAUNCH_BLOCKING=1` was suggested somewhere else to better identify the source of the problem. I am using `spconv v1.2` with `pytorch 1.7.0`. Any ideas?

**Comment by sshaoshuai** [comment]
Have you tried to train other models like SECOND and PointPillar?  
Which dataset does you use?

**Comment by sharma-n** [comment]
@sshaoshuai I used the KITTI dataset. I also tried training the PV-RCNN model which worked perfectly giving me the expected results.

**Comment by sshaoshuai** [comment]
Sorry, I do not know why it happens. Maybe you could try to use smaller batch_size like 3 for training with PartA2.

**Comment by ArtificialCleverness** [comment]
Have you guys found any solution? I have exactly the same issue with same environment. I also noticed that any batch size greater than one can cause this issue, but no prob with batch size 1.

**Comment by MartinHahner** [comment]
I believe that this error is strictly related to **spconv v1.2**.
I recently upgraded my environment to use `spconv v1.2` instead of `spconv v1.0` and it worked fine before.

When I try to train PartA2 with batch size 1 it unfortunately does not "fix" the issue for me, instead I get another error (see below).

I am using
- boost 1.73.0
- cmake 3.16.5
- cuda 11.0.3
- cudnn 8.0.5
- gcc 6.3.0
- nccl 2.7.8-1
- python 3.8.5

My output of `pip list` is added below.

```python
2021-05-06 14:46:13,241   INFO  CUDA_VISIBLE_DEVICES=0
2021-05-06 14:46:13,249   INFO  batch_size       1
2021-05-06 14:46:13,249   INFO  epochs           80
2021-05-06 14:46:13,249   INFO  workers          4
2021-05-06 14:46:13,249   INFO  ckpt             None
2021-05-06 14:46:13,250   INFO  pretrained_model None
2021-05-06 14:46:13,250   INFO  launcher         none
2021-05-06 14:46:13,250   INFO  tcp_port         18888
2021-05-06 14:46:13,250   INFO  sync_bn          False
2021-05-06 14:46:13,250   INFO  fix_random_seed  False
2021-05-06 14:46:13,250   INFO  ckpt_save_interval 1
2021-05-06 14:46:13,250   INFO  local_rank       0
2021-05-06 14:46:13,250   INFO  max_ckpt_save_num 80
2021-05-06 14:46:13,250   INFO  merge_all_iters_to_one_epoch False
2021-05-06 14:46:13,251   INFO  set_cfgs         None
2021-05-06 14:46:13,251   INFO  max_waiting_mins 0
2021-05-06 14:46:13,251   INFO  start_epoch      0
2021-05-06 14:46:13,251   INFO  save_to_file     False
2021-05-06 14:46:13,251   INFO  log_level        info
2021-05-06 14:46:13,251   INFO  cfg.LOCAL_RANK: 0
2021-05-06 14:46:13,252   INFO  cfg.CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']
2021-05-06 14:46:13,252   INFO
cfg.MODEL = edict()
2021-05-06 14:46:13,255   INFO  cfg.MODEL.NAME: PartA2Net
2021-05-06 14:46:13,255   INFO
cfg.MODEL.VFE = edict()
2021-05-06 14:46:13,255   INFO  cfg.MODEL.VFE.NAME: MeanVFE
2021-05-06 14:46:13,255   INFO
cfg.MODEL.BACKBONE_3D = edict()
2021-05-06 14:46:13,256   INFO  cfg.MODEL.BACKBONE_3D.NAME: UNetV2
2021-05-06 14:46:13,256   INFO
cfg.MODEL.MAP_TO_BEV = edict()
2021-05-06 14:46:13,256   INFO  cfg.MODEL.MAP_TO_BEV.NAME: HeightCompression
2021-05-06 14:46:13,256   INFO  cfg.MODEL.MAP_TO_BEV.NUM_BEV_FEATURES: 256
2021-05-06 14:46:13,256   INFO
cfg.MODEL.BACKBONE_2D = edict()
2021-05-06 14:46:13,256   INFO  cfg.MODEL.BACKBONE_2D.NAME: BaseBEVBackbone
2021-05-06 14:46:13,256   INFO  cfg.MODEL.BACKBONE_2D.LAYER_NUMS: [5, 5]
2021-05-06 14:46:13,256   INFO  cfg.MODEL.BACKBONE_2D.LAYER_STRIDES: [1, 2]
2021-05-06 14:46:13,257   INFO  cfg.MODEL.BACKBONE_2D.NUM_FILTERS: [128, 256]
2021-05-06 14:46:13,257   INFO  cfg.MODEL.BACKBONE_2D.UPSAMPLE_STRIDES: [1, 2]
2021-05-06 14:46:13,257   INFO  cfg.MODEL.BACKBONE_2D.NUM_UPSAMPLE_FILTERS: [256, 256]
2021-05-06 14:46:13,257   INFO
cfg.MODEL.DENSE_HEAD = edict()
2021-05-06 14:46:13,257   INFO  cfg.MODEL.DENSE_HEAD.NAME: AnchorHeadSingle
2021-05-06 14:46:13,257   INFO  cfg.MODEL.DENSE_HEAD.CLASS_AGNOSTIC: False
2021-05-06 14:46:13,257   INFO  cfg.MODEL.DENSE_HEAD.USE_DIRECTION_CLASSIFIER: True
2021-05-06 14:46:13,257   INFO  cfg.MODEL.DENSE_HEAD.DIR_OFFSET: 0.78539
2021-05-06 14:46:13,257   INFO  cfg.MODEL.DENSE_HEAD.DIR_LIMIT_OFFSET: 0.0
2021-05-06 14:46:13,258   INFO  cfg.MODEL.DENSE_HEAD.NUM_DIR_BINS: 2
2021-05-06 14:46:13,258   INFO  cfg.MODEL.DENSE_HEAD.ANCHOR_GENERATOR_CONFIG: [{'class_name': 'Car', 'anchor_sizes': [[3.9, 1.6, 1.56]], 'anchor_rotations': [0, 1.57], 'anchor_bottom_heights': [-1.78], 'align_center': False, 'feature_map_stride': 8, 'matched_threshold': 0.6, 'unmatched_threshold': 0.45}, {'class_name': 'Pedestrian', 'anchor_sizes': [[0.8, 0.6, 1.73]], 'anchor_rotations': [0, 1.57], 'anchor_bottom_heights': [-1.78], 'align_center': False, 'feature_map_stride': 8, 'matched_threshold': 0.5, 'unmatched_threshold': 0.35}, {'class_name': 'Cyclist', 'anchor_sizes': [[1.76, 0.6, 1.73]], 'anchor_rotations': [0, 1.57], 'anchor_bottom_heights': [-1.78], 'align_center': False, 'feature_map_stride': 8, 'matched_threshold': 0.5, 'unmatched_threshold': 0.35}]
2021-05-06 14:46:13,258   INFO
cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG = edict()
2021-05-06 14:46:13,258   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.NAME: AxisAlignedTargetAssigner
2021-05-06 14:46:13,258   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.POS_FRACTION: -1.0
2021-05-06 14:46:13,258   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.SAMPLE_SIZE: 512
2021-05-06 14:46:13,258   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.NORM_BY_NUM_EXAMPLES: False
2021-05-06 14:46:13,259   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.MATCH_HEIGHT: False
2021-05-06 14:46:13,259   INFO  cfg.MODEL.DENSE_HEAD.TARGET_ASSIGNER_CONFIG.BOX_CODER: ResidualCoder
2021-05-06 14:46:13,259   INFO
cfg.MODEL.DENSE_HEAD.LOSS_CONFIG = edict()
2021-05-06 14:46:13,259   INFO
cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS = edict()
2021-05-06 14:46:13,259   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.cls_weight: 1.0
2021-05-06 14:46:13,259   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.loc_weight: 2.0
2021-05-06 14:46:13,259   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.dir_weight: 0.2
2021-05-06 14:46:13,259   INFO  cfg.MODEL.DENSE_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
2021-05-06 14:46:13,259   INFO
cfg.MODEL.POINT_HEAD = edict()
2021-05-06 14:46:13,260   INFO  cfg.MODEL.POINT_HEAD.NAME: PointIntraPartOffsetHead
2021-05-06 14:46:13,260   INFO  cfg.MODEL.POINT_HEAD.CLS_FC: []
2021-05-06 14:46:13,260   INFO  cfg.MODEL.POINT_HEAD.PART_FC: []
2021-05-06 14:46:13,260   INFO  cfg.MODEL.POINT_HEAD.CLASS_AGNOSTIC: True
2021-05-06 14:46:13,260   INFO
cfg.MODEL.POINT_HEAD.TARGET_CONFIG = edict()
2021-05-06 14:46:13,260   INFO  cfg.MODEL.POINT_HEAD.TARGET_CONFIG.GT_EXTRA_WIDTH: [0.2, 0.2, 0.2]
2021-05-06 14:46:13,260   INFO
cfg.MODEL.POINT_HEAD.LOSS_CONFIG = edict()
2021-05-06 14:46:13,260   INFO  cfg.MODEL.POINT_HEAD.LOSS_CONFIG.LOSS_REG: smooth-l1
2021-05-06 14:46:13,261   INFO
cfg.MODEL.POINT_HEAD.LOSS_CONFIG.LOSS_WEIGHTS = edict()
2021-05-06 14:46:13,261   INFO  cfg.MODEL.POINT_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.point_cls_weight: 1.0
2021-05-06 14:46:13,261   INFO  cfg.MODEL.POINT_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.point_part_weight: 1.0
2021-05-06 14:46:13,261   INFO
cfg.MODEL.ROI_HEAD = edict()
2021-05-06 14:46:13,261   INFO  cfg.MODEL.ROI_HEAD.NAME: PartA2FCHead
2021-05-06 14:46:13,261   INFO  cfg.MODEL.ROI_HEAD.CLASS_AGNOSTIC: True
2021-05-06 14:46:13,261   INFO  cfg.MODEL.ROI_HEAD.SHARED_FC: [256, 256, 256]
2021-05-06 14:46:13,261   INFO  cfg.MODEL.ROI_HEAD.CLS_FC: [256, 256]
2021-05-06 14:46:13,262   INFO  cfg.MODEL.ROI_HEAD.REG_FC: [256, 256]
2021-05-06 14:46:13,262   INFO  cfg.MODEL.ROI_HEAD.DP_RATIO: 0.3
2021-05-06 14:46:13,262   INFO  cfg.MODEL.ROI_HEAD.SEG_MASK_SCORE_THRESH: 0.3
2021-05-06 14:46:13,262   INFO
cfg.MODEL.ROI_HEAD.NMS_CONFIG = edict()
2021-05-06 14:46:13,262   INFO
cfg.MODEL.ROI_HEAD.NMS_CONFIG.TRAIN = edict()
2021-05-06 14:46:13,262   INFO  cfg.MODEL.ROI_HEAD.NMS_CONFIG.TRAIN.NMS_TYPE: nms_gpu
2021-05-06 14:46:13,262   INFO  cfg.MODEL.ROI_HEAD.NMS_CONFIG.TRAIN.MULTI_CLASSES_NMS: False
2021-05-06 14:46:13,262   INFO  cfg.MODEL.ROI_HEAD.NMS_CONFIG.TRAIN.NMS_PRE_MAXSIZE: 9000
2021-05-06 14:46:13,263   INFO  cfg.MODEL.ROI_HEAD.NMS_CONFIG.TRAIN.NMS_POST_MAXSIZE: 512
2021-05-06 14:46:13,263   INFO  cfg.MODEL.ROI_HEAD.NMS_CONFIG.TRAIN.NMS_THRESH: 0.8
2021-05-06 14:46:13,263   INFO
cfg.MODEL.ROI_HEAD.NMS_CONFIG.TEST = edict()
2021-05-06 14:46:13,263   INFO  cfg.MODEL.ROI_HEAD.NMS_CONFIG.TEST.NMS_TYPE: nms_gpu
2021-05-06 14:46:13,263   INFO  cfg.MODEL.ROI_HEAD.NMS_CONFIG.TEST.MULTI_CLASSES_NMS: False
2021-05-06 14:46:13,263   INFO  cfg.MODEL.ROI_HEAD.NMS_CONFIG.TEST.NMS_PRE_MAXSIZE: 1024
2021-05-06 14:46:13,263   INFO  cfg.MODEL.ROI_HEAD.NMS_CONFIG.TEST.NMS_POST_MAXSIZE: 100
2021-05-06 14:46:13,263   INFO  cfg.MODEL.ROI_HEAD.NMS_CONFIG.TEST.NMS_THRESH: 0.7
2021-05-06 14:46:13,263   INFO
cfg.MODEL.ROI_HEAD.ROI_AWARE_POOL = edict()
2021-05-06 14:46:13,263   INFO  cfg.MODEL.ROI_HEAD.ROI_AWARE_POOL.POOL_SIZE: 12
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.ROI_AWARE_POOL.NUM_FEATURES: 128
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.ROI_AWARE_POOL.MAX_POINTS_PER_VOXEL: 128
2021-05-06 14:46:13,264   INFO
cfg.MODEL.ROI_HEAD.TARGET_CONFIG = edict()
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.TARGET_CONFIG.BOX_CODER: ResidualCoder
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.TARGET_CONFIG.ROI_PER_IMAGE: 128
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.TARGET_CONFIG.FG_RATIO: 0.5
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.TARGET_CONFIG.SAMPLE_ROI_BY_EACH_CLASS: True
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.TARGET_CONFIG.CLS_SCORE_TYPE: roi_iou
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.TARGET_CONFIG.CLS_FG_THRESH: 0.75
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.TARGET_CONFIG.CLS_BG_THRESH: 0.25
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.TARGET_CONFIG.CLS_BG_THRESH_LO: 0.1
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.TARGET_CONFIG.HARD_BG_RATIO: 0.8
2021-05-06 14:46:13,264   INFO  cfg.MODEL.ROI_HEAD.TARGET_CONFIG.REG_FG_THRESH: 0.65
2021-05-06 14:46:13,264   INFO
cfg.MODEL.ROI_HEAD.LOSS_CONFIG = edict()
2021-05-06 14:46:13,265   INFO  cfg.MODEL.ROI_HEAD.LOSS_CONFIG.CLS_LOSS: BinaryCrossEntropy
2021-05-06 14:46:13,265   INFO  cfg.MODEL.ROI_HEAD.LOSS_CONFIG.REG_LOSS: smooth-l1
2021-05-06 14:46:13,265   INFO  cfg.MODEL.ROI_HEAD.LOSS_CONFIG.CORNER_LOSS_REGULARIZATION: True
2021-05-06 14:46:13,265   INFO
cfg.MODEL.ROI_HEAD.LOSS_CONFIG.LOSS_WEIGHTS = edict()
2021-05-06 14:46:13,265   INFO  cfg.MODEL.ROI_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.rcnn_cls_weight: 1.0
2021-05-06 14:46:13,265   INFO  cfg.MODEL.ROI_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.rcnn_reg_weight: 1.0
2021-05-06 14:46:13,265   INFO  cfg.MODEL.ROI_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.rcnn_corner_weight: 1.0
2021-05-06 14:46:13,265   INFO  cfg.MODEL.ROI_HEAD.LOSS_CONFIG.LOSS_WEIGHTS.code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
2021-05-06 14:46:13,265   INFO
cfg.MODEL.POST_PROCESSING = edict()
2021-05-06 14:46:13,265   INFO  cfg.MODEL.POST_PROCESSING.RECALL_THRESH_LIST: [0.3, 0.5, 0.7]
2021-05-06 14:46:13,265   INFO  cfg.MODEL.POST_PROCESSING.SCORE_THRESH: 0.1
2021-05-06 14:46:13,265   INFO  cfg.MODEL.POST_PROCESSING.OUTPUT_RAW_SCORE: False
2021-05-06 14:46:13,265   INFO  cfg.MODEL.POST_PROCESSING.EVAL_METRIC: kitti
2021-05-06 14:46:13,265   INFO
cfg.MODEL.POST_PROCESSING.NMS_CONFIG = edict()
2021-05-06 14:46:13,266   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.MULTI_CLASSES_NMS: False
2021-05-06 14:46:13,266   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_TYPE: nms_gpu
2021-05-06 14:46:13,266   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_THRESH: 0.1
2021-05-06 14:46:13,266   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_PRE_MAXSIZE: 4096
2021-05-06 14:46:13,266   INFO  cfg.MODEL.POST_PROCESSING.NMS_CONFIG.NMS_POST_MAXSIZE: 500
2021-05-06 14:46:13,266   INFO
cfg.OPTIMIZATION = edict()
2021-05-06 14:46:13,266   INFO  cfg.OPTIMIZATION.BATCH_SIZE_PER_GPU: 1
2021-05-06 14:46:13,266   INFO  cfg.OPTIMIZATION.NUM_EPOCHS: 80
2021-05-06 14:46:13,266   INFO  cfg.OPTIMIZATION.OPTIMIZER: adam_onecycle
2021-05-06 14:46:13,266   INFO  cfg.OPTIMIZATION.LR: 0.01
2021-05-06 14:46:13,266   INFO  cfg.OPTIMIZATION.WEIGHT_DECAY: 0.01
2021-05-06 14:46:13,266   INFO  cfg.OPTIMIZATION.MOMENTUM: 0.9
2021-05-06 14:46:13,266   INFO  cfg.OPTIMIZATION.MOMS: [0.95, 0.85]
2021-05-06 14:46:13,266   INFO  cfg.OPTIMIZATION.PCT_START: 0.4
2021-05-06 14:46:13,267   INFO  cfg.OPTIMIZATION.DIV_FACTOR: 10
2021-05-06 14:46:13,267   INFO  cfg.OPTIMIZATION.DECAY_STEP_LIST: [35, 45]
2021-05-06 14:46:13,267   INFO  cfg.OPTIMIZATION.LR_DECAY: 0.1
2021-05-06 14:46:13,267   INFO  cfg.OPTIMIZATION.LR_CLIP: 1e-07
2021-05-06 14:46:13,267   INFO  cfg.OPTIMIZATION.LR_WARMUP: False
2021-05-06 14:46:13,267   INFO  cfg.OPTIMIZATION.WARMUP_EPOCH: 1
2021-05-06 14:46:13,267   INFO  cfg.OPTIMIZATION.GRAD_NORM_CLIP: 10
2021-05-06 14:46:13,267   INFO  cfg.TAG: PartA2
2021-05-06 14:46:17,384   INFO  PartA2Net(
  (vfe): MeanVFE()
  (backbone_3d): UNetV2(
    (conv_input): SparseSequential(
      (0): SubMConv3d()
      (1): BatchNorm1d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (conv1): SparseSequential(
      (0): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
    )
    (conv2): SparseSequential(
      (0): SparseSequential(
        (0): SparseConv3d()
        (1): BatchNorm1d(32, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (1): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(32, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (2): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(32, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
    )
    (conv3): SparseSequential(
      (0): SparseSequential(
        (0): SparseConv3d()
        (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (1): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (2): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
    )
    (conv4): SparseSequential(
      (0): SparseSequential(
        (0): SparseConv3d()
        (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (1): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (2): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
    )
    (conv_out): SparseSequential(
      (0): SparseConv3d()
      (1): BatchNorm1d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (conv_up_t4): SparseBasicBlock(
      (conv1): SubMConv3d()
      (bn1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (relu): ReLU()
      (conv2): SubMConv3d()
      (bn2): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
    )
    (conv_up_m4): SparseSequential(
      (0): SubMConv3d()
      (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (inv_conv4): SparseSequential(
      (0): SparseInverseConv3d()
      (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (conv_up_t3): SparseBasicBlock(
      (conv1): SubMConv3d()
      (bn1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (relu): ReLU()
      (conv2): SubMConv3d()
      (bn2): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
    )
    (conv_up_m3): SparseSequential(
      (0): SubMConv3d()
      (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (inv_conv3): SparseSequential(
      (0): SparseInverseConv3d()
      (1): BatchNorm1d(32, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (conv_up_t2): SparseBasicBlock(
      (conv1): SubMConv3d()
      (bn1): BatchNorm1d(32, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (relu): ReLU()
      (conv2): SubMConv3d()
      (bn2): BatchNorm1d(32, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
    )
    (conv_up_m2): SparseSequential(
      (0): SubMConv3d()
      (1): BatchNorm1d(32, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (inv_conv2): SparseSequential(
      (0): SparseInverseConv3d()
      (1): BatchNorm1d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (conv_up_t1): SparseBasicBlock(
      (conv1): SubMConv3d()
      (bn1): BatchNorm1d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (relu): ReLU()
      (conv2): SubMConv3d()
      (bn2): BatchNorm1d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
    )
    (conv_up_m1): SparseSequential(
      (0): SubMConv3d()
      (1): BatchNorm1d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
      (2): ReLU()
    )
    (conv5): SparseSequential(
      (0): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(16, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
    )
  )
  (map_to_bev_module): HeightCompression()
  (pfe): None
  (backbone_2d): BaseBEVBackbone(
    (blocks): ModuleList(
      (0): Sequential(
        (0): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
        (1): Conv2d(256, 128, kernel_size=(3, 3), stride=(1, 1), bias=False)
        (2): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (3): ReLU()
        (4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (5): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (6): ReLU()
        (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (8): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (9): ReLU()
        (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (11): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (12): ReLU()
        (13): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (14): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (15): ReLU()
        (16): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (17): BatchNorm2d(128, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (18): ReLU()
      )
      (1): Sequential(
        (0): ZeroPad2d(padding=(1, 1, 1, 1), value=0.0)
        (1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), bias=False)
        (2): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (3): ReLU()
        (4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (5): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (6): ReLU()
        (7): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (8): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (9): ReLU()
        (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (11): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (12): ReLU()
        (13): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (14): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (15): ReLU()
        (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (17): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (18): ReLU()
      )
    )
    (deblocks): ModuleList(
      (0): Sequential(
        (0): ConvTranspose2d(128, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (1): Sequential(
        (0): ConvTranspose2d(256, 256, kernel_size=(2, 2), stride=(2, 2), bias=False)
        (1): BatchNorm2d(256, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
    )
  )
  (dense_head): AnchorHeadSingle(
    (cls_loss_func): SigmoidFocalClassificationLoss()
    (reg_loss_func): WeightedSmoothL1Loss()
    (dir_loss_func): WeightedCrossEntropyLoss()
    (conv_cls): Conv2d(512, 18, kernel_size=(1, 1), stride=(1, 1))
    (conv_box): Conv2d(512, 42, kernel_size=(1, 1), stride=(1, 1))
    (conv_dir_cls): Conv2d(512, 12, kernel_size=(1, 1), stride=(1, 1))
  )
  (point_head): PointIntraPartOffsetHead(
    (cls_loss_func): SigmoidFocalClassificationLoss()
    (cls_layers): Sequential(
      (0): Linear(in_features=16, out_features=1, bias=True)
    )
    (part_reg_layers): Sequential(
      (0): Linear(in_features=16, out_features=3, bias=True)
    )
  )
  (roi_head): PartA2FCHead(
    (proposal_target_layer): ProposalTargetLayer()
    (reg_loss_func): WeightedSmoothL1Loss()
    (SA_modules): ModuleList()
    (conv_part): SparseSequential(
      (0): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (1): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
    )
    (conv_rpn): SparseSequential(
      (0): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (1): SparseSequential(
        (0): SubMConv3d()
        (1): BatchNorm1d(64, eps=0.001, momentum=0.01, affine=True, track_running_stats=True)
        (2): ReLU()
      )
    )
    (shared_fc_layer): Sequential(
      (0): Conv1d(221184, 256, kernel_size=(1,), stride=(1,), bias=False)
      (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Dropout(p=0.3, inplace=False)
      (4): Conv1d(256, 256, kernel_size=(1,), stride=(1,), bias=False)
      (5): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): ReLU()
      (7): Dropout(p=0.3, inplace=False)
      (8): Conv1d(256, 256, kernel_size=(1,), stride=(1,), bias=False)
      (9): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (10): ReLU()
    )
    (cls_layers): Sequential(
      (0): Conv1d(256, 256, kernel_size=(1,), stride=(1,), bias=False)
      (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Dropout(p=0.3, inplace=False)
      (4): Conv1d(256, 256, kernel_size=(1,), stride=(1,), bias=False)
      (5): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): ReLU()
      (7): Conv1d(256, 1, kernel_size=(1,), stride=(1,))
    )
    (reg_layers): Sequential(
      (0): Conv1d(256, 256, kernel_size=(1,), stride=(1,), bias=False)
      (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Dropout(p=0.3, inplace=False)
      (4): Conv1d(256, 256, kernel_size=(1,), stride=(1,), bias=False)
      (5): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (6): ReLU()
      (7): Conv1d(256, 7, kernel_size=(1,), stride=(1,))
    )
    (roiaware_pool3d_layer): RoIAwarePool3d()
  )
)

2021-05-06 14:46:25,341   INFO  **********************start of training**********************

train:   0%|                                           | 0/3469 [00:00<?, ?it/s]

train:   0%|                       | 1/3469 [00:00<49:07,  1.18it/s, total_it=1]

epochs:   0%|                       | 0/80 [00:01<?, ?it/s, loss=8.93, lr=0.001]

epochs:   0%|                       | 0/80 [00:01<?, ?it/s, loss=8.93, lr=0.001]


train:   0%|                       | 2/3469 [00:01<39:58,  1.45it/s, total_it=1]

train:   0%|                       | 2/3469 [00:01<39:58,  1.45it/s, total_it=2]

epochs:   0%|                       | 0/80 [00:01<?, ?it/s, loss=8.08, lr=0.001]

epochs:   0%|                       | 0/80 [00:01<?, ?it/s, loss=8.08, lr=0.001]
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [0,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [1,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [2,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [4,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [5,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [6,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [7,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [8,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [9,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [10,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [14,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [15,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [16,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [17,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [18,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [19,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [20,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [21,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [22,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [23,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [24,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [25,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [29,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [30,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [31,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [32,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [33,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [34,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [35,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [36,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [37,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [38,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [39,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [40,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [41,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [42,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [43,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [44,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [45,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [46,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [47,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [48,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [49,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [50,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [51,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [52,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [53,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [54,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [55,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [56,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [57,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [58,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [59,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [60,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [61,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [62,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/pytorch/aten/src/ATen/native/cuda/Loss.cu:102: operator(): block: [0,0,0], thread: [63,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "train.py", line 265, in <module>
    main()
  File "train.py", line 223, in main
    train_model(model,
  File "/cluster/project/cvl/mhahner/repositories/PCDet/tools/train_utils/train_utils.py", line 134, in train_model
    accumulated_iter, n_errors = train_one_epoch(model, optimizer, train_loader, model_func,
  File "/cluster/project/cvl/mhahner/repositories/PCDet/tools/train_utils/train_utils.py", line 64, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/cluster/project/cvl/mhahner/repositories/PCDet/pcdet/models/__init__.py", line 31, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/cluster/apps/nss/gcc-6.3.0/python_gpu/3.8.5/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cluster/project/cvl/mhahner/repositories/PCDet/pcdet/models/detectors/PartA2_net.py", line 14, in forward
    loss, tb_dict, disp_dict = self.get_training_loss()
  File "/cluster/project/cvl/mhahner/repositories/PCDet/pcdet/models/detectors/PartA2_net.py", line 28, in get_training_loss
    loss_rcnn, tb_dict = self.roi_head.get_loss(tb_dict)
  File "/cluster/project/cvl/mhahner/repositories/PCDet/pcdet/models/roi_heads/roi_head_template.py", line 220, in get_loss
    rcnn_loss_cls, cls_tb_dict = self.get_box_cls_layer_loss(self.forward_ret_dict)
  File "/cluster/project/cvl/mhahner/repositories/PCDet/pcdet/models/roi_heads/roi_head_template.py", line 214, in get_box_cls_layer_loss
    tb_dict = {'rcnn_loss_cls': rcnn_loss_cls.item()}
RuntimeError: CUDA error: device-side assert triggered
```

Here is my environment:
```bash
Package                         Version       Location
------------------------------- ------------- -----------------------------------------------
absl-py                         0.10.0
access                          1.1.3
affine                          2.3.0
aiohttp                         3.7.3
aiohttp-cors                    0.7.0
aioredis                        1.3.1
alabaster                       0.7.12
amply                           0.1.4
aniso8601                       9.0.1
anndata                         0.7.4
anyio                           2.2.0
apex                            0.1
appdirs                         1.4.4
apptools                        5.1.0
argh                            0.26.2
argon2-cffi                     20.1.0
arviz                           0.11.2
ase                             3.20.1
asn1crypto                      1.4.0
astor                           0.8.1
astroid                         2.5.6
astunparse                      1.6.3
async-generator                 1.10
async-timeout                   3.0.1
atomicwrites                    1.4.0
attrs                           20.2.0
audioread                       2.1.9
autopep8                        1.5.6
Babel                           2.8.0
backcall                        0.2.0
beautifulsoup4                  4.9.3
bidict                          0.21.2
bids-validator                  1.5.4
bitstring                       3.1.7
bleach                          3.2.1
blessings                       1.7
bokeh                           2.2.1
Bottleneck                      1.3.2
cachetools                      4.2.2
Cartopy                         0.19.0.post1
certifi                         2020.6.20
cffi                            1.14.3
cfgrib                          0.9.9.0
cftime                          1.2.1
chardet                         3.0.4
cityenergyanalyst               3.22.0
click                           7.1.2
click-plugins                   1.1.1
cligj                           0.7.1
climada                         2.1.1
cloudpickle                     1.6.0
colorama                        0.4.4
colorful                        0.5.4
colorlog                        4.7.2
colorlover                      0.3.0
commonmark                      0.9.1
ConfigArgParse                  1.2.3
configobj                       5.0.6
configparser                    5.0.2
contextily                      1.1.0
coverage                        5.5
cryptography                    3.4.7
cufflinks                       0.17.3
cvxopt                          1.2.6
cycler                          0.10.0
Cython                          0.29.21
dask                            2021.1.1
datrie                          0.8.2
deap                            1.3.1
decorator                       4.4.2
deepdiff                        5.0.2
defusedxml                      0.6.0
Deprecated                      1.2.10
descartes                       1.1.0
dill                            0.3.3
distributed                     2021.1.1
dm-tree                         0.1.5
docker-pycreds                  0.4.0
docopt                          0.6.2
docutils                        0.16
easydict                        1.9
eccodes                         1.3.2
entrypoints                     0.3
envisage                        5.0.0
ephem                           3.7.7.1
esda                            2.3.6
et-xmlfile                      1.0.1
fastprogress                    1.0.0
filelock                        3.0.12
findlibs                        0.0.1
Fiona                           1.8.19
Flask                           1.1.2
flask-restplus                  0.13.0
Flask-SocketIO                  5.0.1
flatbuffers                     1.12
flit                            3.0.0
flit-core                       3.0.0
fsspec                          0.8.5
funcsigs                        1.0.2
future                          0.18.2
gast                            0.3.3
GDAL                            3.1.2
geographiclib                   1.50
geopandas                       0.9.0
geopy                           2.1.0
gevent                          21.1.2
giddy                           2.3.3
gitdb                           4.0.5
gitdb2                          4.0.2
GitPython                       3.1.9
google-api-core                 1.25.0
google-auth                     1.24.0
google-auth-oauthlib            0.4.2
google-pasta                    0.2.0
googleapis-common-protos        1.52.0
googledrivedownloader           0.4
gprMax                          3.1.5
gpustat                         0.6.0
grabbit                         0.2.6
graphtools                      1.5.2
greenlet                        1.0.0
grpcio                          1.32.0
gspread                         3.7.0
gurobipy                        9.1.1
h5py                            2.10.0
haversine                       2.3.0
HeapDict                        1.0.1
hiredis                         1.1.0
html5lib                        1.1
httplib2                        0.19.1
hyperopt                        0.2.4
idna                            2.10
imageio                         2.9.0
imagesize                       1.2.0
importlib-metadata              4.0.1
importlib-resources             5.1.2
inequality                      1.0.0
iniconfig                       1.1.1
install                         1.3.4
ipykernel                       5.3.4
ipython                         7.18.1
ipython-genutils                0.2.0
ipywidgets                      7.5.1
iso3166                         1.0.1
isodate                         0.6.0
isort                           5.8.0
itsdangerous                    1.1.0
jedi                            0.17.2
jeepney                         0.6.0
Jinja2                          2.11.2
joblib                          0.17.0
json5                           0.9.5
jsonpickle                      1.4.1
jsonschema                      3.2.0
jupyter                         1.0.0
jupyter-client                  6.1.7
jupyter-console                 6.2.0
jupyter-contrib-core            0.3.3
jupyter-core                    4.6.3
jupyter-highlight-selected-word 0.2.0
jupyter-packaging               0.7.12
jupyter-server                  1.6.0
jupyterlab                      3.0.13
jupyterlab-pygments             0.1.2
jupyterlab-server               2.4.0
Keras                           2.4.3
Keras-Applications              1.0.8
Keras-Preprocessing             1.1.2
keyring                         23.0.1
kiwisolver                      1.2.0
lapsolver                       1.1.0
lazy-object-proxy               1.6.0
libpysal                        4.4.0
librosa                         0.8.0
llvmlite                        0.35.0
locket                          0.2.1
lxml                            4.6.2
Mako                            1.1.4
mapclassify                     2.4.2
Markdown                        3.2.2
MarkupSafe                      1.1.1
matplotlib                      3.3.2
mccabe                          0.6.1
mercantile                      1.2.1
mgwr                            2.1.2
mistune                         0.8.4
mock                            4.0.2
more-itertools                  8.5.0
mpmath                          1.1.0
msgpack                         1.0.2
multidict                       5.1.0
multiprocess                    0.70.11.1
munch                           2.5.0
natsort                         7.0.1
nbclassic                       0.2.7
nbclient                        0.5.0
nbconvert                       6.0.7
nbformat                        5.0.7
nbsphinx                        0.8.2
nest-asyncio                    1.4.1
netCDF4                         1.5.6
networkx                        2.5
nibabel                         3.1.1
nipy                            0.4.2
nose                            1.3.7
notebook                        6.1.4
num2words                       0.5.10
numba                           0.52.0
numexpr                         2.7.1
numpy                           1.19.2
nvidia-ml-py3                   7.352.0
oauth2client                    4.1.3
oauthlib                        3.1.0
opencensus                      0.7.12
opencensus-context              0.1.2
opencv-contrib-python           4.5.1.48
opencv-python                   4.4.0.46
openpyxl                        3.0.7
opt-einsum                      3.3.0
ordered-set                     4.0.2
osmnx                           1.1.0
overpy                          0.6
packaging                       20.4
pandas                          1.1.3
pandas-datareader               0.9.0
pandoc                          1.0.2
pandocfilters                   1.4.2
parso                           0.7.1
partd                           1.1.0
pathos                          0.2.7
pathtools                       0.1.2
patsy                           0.5.1
pbr                             5.5.0
pcdet                           0.3.0+52473ef /cluster/project/cvl/mhahner/repositories/PCDet
pexpect                         4.8.0
pickleshare                     0.7.5
Pillow                          7.2.0
Pint                            0.16.1
pip                             21.1.1
pkginfo                         1.7.0
plotly                          4.11.0
pluggy                          0.13.1
ply                             3.11
pointpats                       2.2.0
pooch                           1.3.0
pox                             0.2.9
ppft                            1.6.6.3
prometheus-client               0.8.0
promise                         2.3
prompt-toolkit                  3.0.7
protobuf                        3.14.0
psutil                          5.7.2
ptyprocess                      0.6.0
PuLP                            2.3
py                              1.10.0
py-spy                          0.3.4
py4design-cea                   0.30
pyasn1                          0.4.8
pyasn1-modules                  0.2.8
pybufrkit                       0.2.18
pycodestyle                     2.7.0
pycollada                       0.7.1
pycparser                       2.20
pyepsg                          0.4.0
pyface                          7.3.0
pygame                          2.0.1
pygeos                          0.8
pyglet                          1.5.14
Pygments                        2.7.1
pygraphviz                      1.7
PyGSP                           0.5.1
pylint                          2.8.2
pymc3                           3.11.2
pymongo                         3.11.0
Pyomo                           5.7.3
pyopencl                        2021.1.6
PyOpenGL                        3.1.5
pyparsing                       2.4.7
pyproj                          3.0.1
pypsa                           0.17.1
PyQt5                           5.15.4
PyQt5-Qt5                       5.15.2
PyQt5-sip                       12.8.1
pyqtgraph                       0.12.1
Pyro4                           4.80
pyrsistent                      0.17.3
pysal                           2.4.0
pyshp                           2.1.3
PySocks                         1.7.1
pytest                          6.2.3
pytest-cov                      2.11.1
python-dateutil                 2.8.0
python-engineio                 4.1.0
python-louvain                  0.14
python-socketio                 5.2.1
pytoml                          0.1.21
pytools                         2021.2.6
pytz                            2020.1
PyUtilib                        6.0.0
pyutillib                       0.3.0
PyWavelets                      1.1.1
pyxlsb                          1.0.8
PyYAML                          5.3.1
pyzmq                           19.0.2
qtconsole                       4.7.7
QtPy                            1.9.0
quantecon                       0.5.0
rasterio                        1.2.3
rasterstats                     0.15.0
ratelimiter                     1.2.0.post0
ray                             1.1.0
rdflib                          5.0.0
readme-renderer                 29.0
recommonmark                    0.7.1
redis                           3.5.3
reportlab                       3.5.67
requests                        2.25.1
requests-oauthlib               1.3.0
requests-toolbelt               0.9.1
resampy                         0.2.2
retrying                        1.3.3
rfc3986                         1.4.0
rsa                             4.6
Rtree                           0.9.7
SALib                           1.3.13
scikit-image                    0.17.2
scikit-learn                    0.23.2
scipy                           1.6.3
seaborn                         0.11.1
SecretStorage                   3.3.1
segregation                     1.5.0
semver                          2.13.0
Send2Trash                      1.5.0
sentry-sdk                      1.0.0
serpent                         1.30.2
setuptools                      47.1.0
Shapely                         1.7.1
shortuuid                       1.0.1
simplegeneric                   0.8.1
simplejson                      3.17.2
six                             1.15.0
smmap                           3.0.4
smmap2                          3.0.1
snakemake                       5.26.1
sniffio                         1.2.0
snowballstemmer                 2.0.0
snuggs                          1.4.7
sortedcontainers                2.3.0
SoundFile                       0.10.3.post1
soupsieve                       2.2.1
spaghetti                       1.5.6
spconv                          1.2.1
spglm                           1.0.8
Sphinx                          3.2.1
sphinxcontrib-applehelp         1.0.2
sphinxcontrib-devhelp           1.0.2
sphinxcontrib-htmlhelp          1.0.3
sphinxcontrib-jsmath            1.0.1
sphinxcontrib-qthelp            1.0.3
sphinxcontrib-serializinghtml   1.1.4
sphinxcontrib-websupport        1.2.4
spint                           1.0.7
splot                           1.1.3
spopt                           0.1.1
spreg                           1.2.2
spvcm                           0.3.0
staticmap                       0.5.5
statsmodels                     0.12.0
subprocess32                    3.5.4
svg.path                        4.0.2
sympy                           1.6.2
tables                          3.6.1
tabulate                        0.8.9
tasklogger                      1.0.0
tblib                           1.7.0
tensorboard                     2.4.0
tensorboard-plugin-wit          1.7.0
tensorboardX                    2.2
tensorflow                      2.4.0
tensorflow-estimator            2.4.0
tensorflow-probability          0.12.0
termcolor                       1.1.0
terminado                       0.9.1
terminaltables                  3.1.0
testpath                        0.4.4
Theano                          1.0.5
Theano-PyMC                     1.1.2
threadpoolctl                   2.1.0
tifffile                        2020.10.1
timezonefinder                  5.2.0
tobler                          0.7.0
toml                            0.10.2
toolz                           0.11.1
toposort                        1.5
torch                           1.7.1+cu110
torch-cluster                   1.5.8
torch-geometric                 1.6.3
torch-scatter                   2.0.5
torch-sparse                    0.6.8
torch-spline-conv               1.2.0
torchaudio                      0.7.2
torchvision                     0.8.2+cu110
tornado                         6.1
tqdm                            4.50.0
traitlets                       5.0.4
traits                          6.2.0
traitsui                        7.1.1
trimesh                         3.9.1
twine                           3.4.1
typing-extensions               3.7.4.3
urllib3                         1.26.4
utm                             0.7.0
wandb                           0.10.29
waymo-open-dataset-tf-2-4-0     1.2.0
wcwidth                         0.2.5
webencodings                    0.5.1
Werkzeug                        1.0.1
wheel                           0.35.1
widgetsnbextension              3.5.1
wntr                            0.3.0
wrapt                           1.12.1
xarray                          0.17.0
xlrd                            2.0.1
XlsxWriter                      1.4.0
xlwt                            1.3.0
xmlrunner                       1.7.7
xxhash                          2.0.0
yarl                            1.6.3
zict                            2.0.0
zipp                            3.3.0
zope.event                      4.5.0
zope.interface                  5.4.0

```

**Comment by MartinHahner** [comment]
Downgraded to 
- torch 1.4
- cuda 10.1.243
- cudnn 7.6.4
- spconv 1.0

Also see [here](https://github.com/traveller59/spconv/issues/78#issuecomment-631599062) and [there](https://github.com/traveller59/spconv/issues/12#issuecomment-457635066).
Now the training of PartA2 works again.

**Comment by xuxiaoxxxx** [comment]
> 

my environment is the same as yours, but I still encount this problem.
